-- use projectManagementSystem
-- select * from Projects
-- CREATE PROCEDURE UpdateProjectStatus
--    @AssignedUserEmail NVARCHAR(255),
--    @NewStatus NVARCHAR(255)
-- AS
-- BEGIN
--     UPDATE Projects
--     SET projectStatus = @NewStatus
--     WHERE AssignedUserEmail = @AssignedUserEmail;
-- END;
