post http://localhost:4600/user/register
Content-Type: application/json
{
    "userName":"perez",
    "email":"perez@gmail.com",
    "password":"12345678",
    "phone_no":"0711900000"
}

###
#login user
POST http://localhost:4600/user/login
Content-Type: application/json

{
    "email":"9superbikes@gmail.com",
    "password":"12345678"
}


###
#get all user

get http://localhost:4600/user/
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI1YWJjNjAxMy0xNWYyLTQzNmQtODgzOC1mYzRhZDMwZDRhMTAiLCJ1c2VyTmFtZSI6IlNhbmRyYSBDaGVnZSIsImVtYWlsIjoiOXN1cGVyYmlrZXNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiV2VsY29tZWQiOmZhbHNlLCJFbWFpbFNlbnQiOmZhbHNlLCJpc0Fzc2lnbmVkIjpmYWxzZSwiaWF0IjoxNjk5MzgzMDkzLCJleHAiOjE2OTkzODY2OTN9.ZdVohSG6WiLkRzYwQE6U-zATvijEcDtqS51UbhQ7_Rk


###
#check user details
GET http://localhost:4600/user/check_user_details
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI3MWU0OWQ3Mi0yNjIyLTRiZWItOTQxYy1kMDZiZGJkZjhkMzciLCJ1c2VyTmFtZSI6Ik1pY2hhZWwgT3RpZW5vIiwiZW1haWwiOiJtaWNoZWFsdmVudW0wMDdAZ21haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2UsIkFzc2lnbmVkUHJvamVjdElEIjpudWxsLCJFbWFpbFNlbnQiOmZhbHNlLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2OTg4NzU0NTIsImV4cCI6MTY5ODg3OTA1Mn0.qsQi-r_jZVoAihToyO2HRNOOEZttROjDuBWIm1-lofA



###
#admin assign project

POST http://localhost:4600/project/assignProject
Content-Type: application/json

{
   
    "projectName": "BackgroundSerices",
    "projectDescription": "build company chatbot",
    "endDate": "2023-11-9",
    "AssignedUserEmail": "cylvonnen@gmail.com",  
    "AssignedUserName": "Joshua Ochieng"  
}

###
#delete project
DELETE  http://localhost:4600/project/deleteProject
Content-Type: application/json

{
   
    "projectID":"8dd3c8a8-c87c-4e7a-ab55-44ead598ca4b"
   
}


###
#get all projects
get  http://localhost:4600/project/

###
#get single project
get  http://localhost:4600/project/singleProject
Content-Type: application/json

{
   
    "AssignedUserEmail":"mikvenu9@gmail.com"
   
}

###
#update completed project
post http://localhost:4600/project/updateProject
Content-Type: application/json

{
   
    "projectID":"1da4856b-edde-47f2-90d4-603913e26b7f"
   
}

###
#fetch All Users

get http://localhost:4600/project/getUsers


###
#user updates status

post http://localhost:4600/project/projectStatus
Content-Type: application/json

{
   
    "AssignedUserEmail":"dankinyi99@gmail.com",
    "NewStatus":"halfway there"
   
}

###
#get project status
get http://localhost:4600/project/getStatus
Content-Type: application/json

{
   
    "AssignedUserEmail":"dankinyi99@gmail.com"
   
}







